### ISSUE TITLE
chatgpt-abfrage beschleunigen

### ISSUE THREAD

**Issue by m1cm1c** [secguro/secguro-cli#126]
nur diff in unified diff format statt vollständige änderung anfordern

**Comment by m1cm1c** [comment]
unified diff format bekommt chat gpt nicht hin

wenn man es dazu anweist, etwas im unified diff format oder in git's diff format auszugeben, gibt es einem auch weiterhin die ausgabe in seinem eigenen diff format: ohne zeilenangabe (überhaupt keine @-zeichen) und auch ohne den sonstigen header

wenn man es noch dazu anweist, den header anzugeben und ihm durch nennung eines dateinamens hilfestellung bei header-generierung gibt, gibt es meist ein header an: meist sowas wie

```
diff --git a/file.txt b/file.txt
index 7c69a62..005349d 100644
--- a/file.txt
+++ b/file.txt
@@ -38,7 +38,7 @@ export const defaultNetworks = [
```

oder

```
--- a/file.txt
+++ b/file.txt
@@ -44,7 +44,7 @@
```

oder 

```
--- a/file.txt
+++ b/file.txt
@@ -36,7 +36,7 @@
```

oder

```
file.txt
@@ -33,7 +33,7 @@
```

(das waren die 4 häufigsten; ich hab dasselbe query etliche male ausgeführt)

in keinem fall aber war der patch durch ein bestehendes patch-tool anwendbar, denn die header sind zwar meist vorhanden, aber immer falsch

außerdem habe ich beobachtet, dass der inhalt des diffs nur selten das problem behebt (nur bei gefühlt jedem 5. bis 10. anlauf), wohingegen bei vollständiger ausgabe das problem fast immer behoben wurde

ich sehe nun die folgenden 4 möglichkeiten zum weiteren vorgehen:

1. die optimierung streichen und den nutzer warten lassen
2. in der webapp schon bei chatgpt einen fix anfragen bevor der nutzer auf den button geklickt hat um die scheinbare wartezeit zu verkürzen
3. eigenen code schreiben, der die patches von chat gpt anwendet¹
4. versuchen, den header selbst zu generieren um bereitstehende tools zur diff-anwendung verwenden zu können
5. nur wenige zeilen in chatgpt eingeben um die ausgabe auf diese weise kurz zu halten (keine diffs mehr anfragen)

ich tendiere zu option 3 oder 5. option 4 finde ich am schlechtesten, denn es wirkt auf mich so, dass während der implementierung von option 4 fast alle arbeit, die für option 3 notwendig wäre, gemacht werden muss, aber mit mehr fehler-potential und einer weiteren abhängigkeit

wie siehst du das?




¹ wenn man es nicht darum bittet, patches mit header bereitzustellen, wirken die diffs aufs erste wesentlich einheitlicher. es besteht aber das problem, das meist sehr wenig kontext bereitgestellt wird (die angabe, wie viele zeilen kontext bereitgestellt werden soll, wird scheinbar ignoriert). außerdem weiß ich noch nicht, wie gut die patches dann sind. ich hab bisher immer versucht, zu erzwingen, dass header dabei sind, damit andere tools die patches anwenden können, und das daher noch nicht untersucht

**Comment by MStumpp** [comment]
Ich sehe nicht, warum chatgpt ein diff generieren können soll.

Chatgpt soll den fehlerfreien Code liefern gegeben den fehlerbehafteten Code.

Die Art der Repräsentation findet außerhalb von Chatgpt statt.

Benötigen wir die diff-Repräsentation denn überhaupt noch? Das aktuelle React-Diff-Viewer erwartet den Vorher- und Nachher Code separat. 

Dies entspricht Option 5.

**Comment by m1cm1c** [comment]
Es geht hier überhaupt nicht um etwas optisches oder um eine Repräsentation oder so. Es geht darum, die Abfrage zu beschleunigen. ChatGPT braucht für jedes Ausgabe-Token viel Zeit. Umso länger die Ausgabe, desto länger die Anfrage-Zeit.

**Comment by MStumpp** [comment]
Inwiefern steht dein letzter Kommentar im Widerspruch zu meinem letzten Post?
U.a. aus dem Performance Grund tendiere ich doch zu 5.

Welche Information/Entscheidung benötigst du hier (noch) von mir?

**Comment by m1cm1c** [comment]
Ich hatte es so verstanden, dass du überhaupt nicht verstanden hättest, welches Problem ich versuche zu lösen. Denn sowas wie "Die Aufbereitung in die gewünschte Repräsentation findet außerhalb von Chatgpt statt." ist ja klar. Ich versuche selbstverständlich nicht, ChatGPT als diff tool zu verwenden.

**Comment by m1cm1c** [comment]
Ok, ich versuche Variante 5.

**Comment by m1cm1c** [comment]
implemented in  #164
