### ISSUE TITLE
support für .secguroignore

### ISSUE THREAD

**Issue by m1cm1c** [secguro/secguro-cli#32]

**Comment by m1cm1c** [comment]
.eslintignore unterstützt keinen ausschluss bestimmter regeln

eslint hat nur etwas auf verzeichnis-ebene, das dagegen hilft: man kann in einem verzeichnis eine .eslintrc anlegen, in der man die regel dann für dieses verzeichnis deaktiviert (https://stackoverflow.com/a/41316801) halte ich für unseren anwendungsfall aber nicht für sinnvoll. daher müssen wir wohl unsere eigene syntax für die .secguroignore erfinden. gemäß dem letzten telefonat wäre das:

ignorieren aller regeln:
```
all pathInGitignoreNotation
```


ignorieren einer regel:
```
generic-api-key pathInGitignoreNotation
```

ignorieren von 3 regeln:
```
generic-api-key,yaml.kubernetes.security.allow-privilege-escalation-no-securitycontext.allow-privilege-escalation-no-securitycontext,typescript.react.security.audit.react-jwt-decoded-property.react-jwt-decoded-property pathInGitignoreNotation
```

allerdings wir das recht unübersichtlich, weil die zeilen sehr lang werden. daher wäre etwas absatz-basiertes vielleicht besser:
```
pathInGitignoreNotation
generic-api-key
yaml.kubernetes.security.allow-privilege-escalation-no-securitycontext.allow-privilege-escalation-no-securitycontext
typescript.react.security.audit.react-jwt-decoded-property.react-jwt-decoded-property 
```

oder noch strukturierter in yaml- oder json-notation:
```
pathInGitignoreNotation:
  - generic-api-key
  - yaml.kubernetes.security.allow-privilege-escalation-no-securitycontext.allow-privilege-escalation-no-securitycontext
  - typescript.react.security.audit.react-jwt-decoded-property.react-jwt-decoded-property 
```

```
"pathInGitignoreNotation": [
  "generic-api-key",
  "yaml.kubernetes.security.allow-privilege-escalation-no-securitycontext.allow-privilege-escalation-no-securitycontext",
  "typescript.react.security.audit.react-jwt-decoded-property.react-jwt-decoded-property"
]
```

**Comment by m1cm1c** [comment]
ich denke, dass ich herausgefunden habe, wieso die anderen projekte so hässliche ignore-regeln haben (in semgrep kann man nur ganze dateien ignorieren; bei gitleaks muss man zeilen-nummern angeben; in beiden fällen scheinen keine ignore-regeln, die im code definiert werden, möglich zu sein): es scheint unmöglich zu sein, ein ignore-regelwerk zu definieren, das beim scannen der git-history sinn ergibt. oder fällt dir eines ein?

beispiel 1: man verwendet die ignore-regeln der neuesten revision. wenn dann eine datei, in der ignorierte violations sind, gelöscht wird, werden einem die violations ausgegeben

beispiel 2: man verwendet die ignore-regeln der revision, in der violation eingeführt wurde. wenn dann jemand wie du, von dem 30% der commits "lintfixes" heißen, im nachhinein ignore-regeln hinzufügt, und das in einen neuen commit packt statt den alten zu aktualisieren, wird einem die violation weiterhin ausgegeben

beispiel 3: man verwendet alle ignore-regeln, die man in irgendeiner revision finden kann: eine fälschlicherweise hinzugefügte ignore-regel kann nicht mehr entfernt werden

**Comment by MStumpp** [comment]
Bzgl. .secguroignore

Bevorzuge diese Variante:

path1
optional rule11
optional rule12
path2
optional rule21
optional rule22
<Leerzeichen: 1 oder mehrere Leerzeichen möglich>
path3
optional rule31
optional rule32

Angabe Regeln im File würde ich erstmal weglassen.
Wenn doch, dann vielleicht am ehesten so: 0 oder mehrere Regeln angeben, die fürs ganze File gelten. Die Regeln sollten mit einem Prefix beginnen, z.B.

secguroignore:rule1
secguroignore:rule2

Berücksichtigung von ignore Regeln beim scannen der git-history würde ich ebenso weglassen.
Wenn doch, dann die Regeln der neusten Revision.

**Comment by m1cm1c** [comment]
```
path1
optional rule11
optional rule12
path2
```

Woher weiß das Programm, dass `path2` ein Pfad, aber `optional rule12` kein Pfad ist?

**Comment by MStumpp** [comment]
Via path erkennung => ^(.+)\/([^\/]+)$

**Comment by m1cm1c** [comment]
Du hast doch gesagt, dass wir uns wenn möglich an das halten sollen was eslint macht. Eslint hält sich bei den Pfaden an das was Git macht. Und jetzt möchtest du die üblichsten Pfad-Angaben illegal machen?

**Comment by MStumpp** [comment]
Der Gedanke mit EsLint war eher so gemeint, sich an EsLint zu orientieren, aber weniger das wir nur machen dürfen, was EsLint vorgibt.

Ich kann auch mit der Verpflichtung ein Leerzeichen einzufügen leben. Dann machen wir das mit Leerzeichen.
