### ISSUE TITLE
anzeige von commit message vs commit message summary

### ISSUE THREAD

**Issue by m1cm1c** [secguro/secguro-cli#43]
mir ist aktuell noch nicht klar, was besser ist. sag bescheid, ob du dazu eine meinung hast

**Comment by m1cm1c** [comment]
hab grad die git-integration für semgrep findings fertiggestellt (#44) und dabei die summary verwendet, weil die über git blame einfacher zu bekommen ist. für gitleaks findings wird aber weiterhin die komplette commit message ausgegeben

**Comment by MStumpp** [comment]
Würde wohl erstmal beides ausgeben wenn verfügbar.

Wenn Basic/Expert mode, dann wir hier #https://github.com/secguro/secguro-cli/issues/45

**Comment by m1cm1c** [comment]
beschlossen: nur summary anzeigen

**Comment by m1cm1c** [comment]
implemented in  #53
