### ISSUE TITLE
ausgabe-format

### ISSUE THREAD

**Issue by m1cm1c** [secguro/secguro-cli#45]
aktuelles format:

```
Finding 162:
  detector: semgrep
  rule: generic.secrets.security.detected-generic-api-key.detected-generic-api-key
  file: server/src/helpers/get_or_increase_nonce.ts
  line: 7
  column: 56
  match:   const providerUrl = 'wss://sepolia-ws.chainantic.com?apiKey=Ain9attAgara8irgYan90iDfirufTdaT';
  hint: Generic API Key detected
  commit hash: 0eac3305a9da55315e79f07dfa3699aa755dd3ff
  commit date: 2023-08-17T13:50:52Z
  author: Christoph Michelbach
  author email address: emailaddress@gmail.com
  commit message: Use URLs of our own nodes in script get_or_increase_nonce.ts.
```

vorschlag:

```
Finding 162:
    const providerUrl = 'wss://sepolia-ws.chainantic.com?apiKey=Ain9attAgara8irgYan90iDfirufTdaT';
  rule: generic.secrets.security.detected-generic-api-key.detected-generic-api-key (semgrep)
  location: server/src/helpers/get_or_increase_nonce.ts:7:56
  hint: Generic API Key detected
  commit: 0eac33 (Use URLs of our own nodes in script get_or_increase_nonce.ts.)
  authorship: Christoph Michelbach (emailaddress@gmail.com) 2023-08-17T13:50:52Z
```

was hältst du davon?

außerdem zur diskussion: match um whitespace trimmen, so dass das nicht nach zufälliger einrückung aussieht? (die einrückung sieht eigentlich gar nicht schlecht aus, aber nur, weil die zeile zufällig mit 2 leerzeichen beginnt. ich finde, dass man den match durchaus immer um 2 leerzeichen relativ zu den stichpunkten (um 4 leerzeichen relativ zum zeilenanfang) einrücken kann, aber finde, dass man whitespace am anfang der zeile vermutlich wegtrimmen sollte)

(echtes beispiel; API key und email-adresse durch gleich lange andere strings ersetzt, weil das repo öffentlich ist)

**Comment by MStumpp** [comment]
Auf den ersten Blick finde ich die aktuelle Variante besser. Was ist dein Grund die Infos auf weniger Zeilen aufzuteilen? Damit  der Inhalt auf der Konsole weniger Zeilen erfordert und man damit weniger scrollen muss?

**Comment by m1cm1c** [comment]
> Was ist dein Grund die Infos auf weniger Zeilen aufzuteilen? Damit der Inhalt auf der Konsole weniger Zeilen erfordert und man damit weniger scrollen muss?

Ja, und außerdem wirkt es aktuell schon sehr tabellarisch.

**Comment by m1cm1c** [comment]
beschlossen: nicht ändern
