### ISSUE TITLE
ausgabe des ortes eines findings

### ISSUE THREAD

**Issue by m1cm1c** [secguro/secguro-cli#67]
ich möchte nochmal nachfragen, weil wir in dem anruf neulich bzgl diesem thema lange einander missverstanden haben

## Definitionen
- ort eines findings: dateipfad, zeilennummer (anfang), spaltennummer (anfang)
- aktueller ort: ort, an dem das finding im working directory steht
- historischer ort: ort, an dem das finding zu einer bestimmten revision stand (sofern nicht anders benannt, bezieht sich das auf die revision, in der der inhalt, der das finding ausmacht, eingeführt wurde)

## Frage
ist das folgende anforderungsverständnis korrekt?

- deaktivierter git mode: es werden keinerlei git-bezogene informationen angezeigt. insbesondere wird nur der aktuelle ort angezeigt
- aktivierter git mode: es wird der historische ort angezeigt. falls der aktuelle ort vom historischen ort abweicht, wird auch der aktuelle ort angezeigt

**Comment by MStumpp** [comment]
Passt so

**Comment by m1cm1c** [comment]
größtenteils in 1e27648 implementiert

bekanntes problem: es wird der neueste ort angezeigt

daraus resultierend teilprobleme:
- es wird nie angezeigt, dass das geheimnis in der aktuellen revision nicht mehr existiert
- es wird teilweise ein commit hash angezeigt, der gar nicht im aktuellen branch ist

**Comment by m1cm1c** [comment]
die beiden genannten probleme hab ich in 1e50531 und 245087b gefixt

**Comment by m1cm1c** [comment]
ich hab das wie oben beschrieben implementiert, mit der abweichung, dass "location" sich auf den aktuellen ort bezieht und es dementsprechend als gegensatz dazu nicht "current location" sondern "historical location" gibt, weil ich denke, dass das intuitiver verständlich ist

aktuell sieht es so aus:

![image](https://github.com/secguro/secguro-cli/assets/11382432/f41d4ce4-4b0c-471e-8dea-ee24228fa69a)


bzw. wenn es aktuell nicht mehr existiert:

![image](https://github.com/secguro/secguro-cli/assets/11382432/dd67f39c-d04b-4c95-84f8-a223a93d5744)

**Comment by m1cm1c** [comment]
außerdem hab ich 2127d18 implementiert, dass immer der commit angezeigt wird, in dem die zeile hingefügt wurde. ich dachte, dass das schon vorher so gewesen sei, aber es hat sich herausgestellt, dass gitleaks nicht immer diesen commit ausgibt, sondern manchmal auch einfach irgendeinen commit, in dem das geheimnis vorkommt, auch wenn es im parent commit schon vorgekommen ist
